#%RAML 1.0 DataType

additionalProperties: false
properties:
  accountNum:
    type: string
    displayName: Account Number
  bankName:
    type: string
    displayName: Name of the Bank
  confirmContactNum:
    type: string
    displayName: Contact Number Confirmation
  confirmEmail:
    type: string
    displayName: Email Confirmation
  policyNumber:
    type: string
    displayName: Policy Number
  quoteId:
    type: string
    displayName: Quote Id
  id?:
    type: string
    displayName: Policy Id
